FROM rust:1.76 as builder
WORKDIR /usr/src/rust-api
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/rust-api/target/release/sentineliq-api /usr/local/bin/
EXPOSE 8080
CMD ["sentineliq-api"]
