FROM python:3.11-slim
WORKDIR /home/spiderfoot
RUN apt-get update && apt-get install -y git libxml2-dev libxslt1-dev zlib1g-dev gcc && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/smicallef/spiderfoot.git /home/spiderfoot
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5001
CMD ["python", "sf.py", "-l", "0.0.0.0:5001"]
